// web/src/main.tsx
import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { RouterProvider, createRouter } from "@tanstack/react-router"
import "./index.css"

// Import the route tree generated by the Vite plugin
import { routeTree } from "./routeTree.gen"

// 1. Create a new React Query client instance
const queryClient = new QueryClient()

// 2. Create a new router instance using the generated route tree
const router = createRouter({
  routeTree,
  // Pass the query client to the router context if you want to use it in route loaders
  context: {
    queryClient,
  },
  // Set default defaultPreload to 'intent' to preload routes on hover
  defaultPreload: "intent",
})

// 3. Register the router instance for strict type safety
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router
  }
}

// 4. Render the app wrapped in both providers
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>
)
